package org.marketsuite.component.button;

import java.util.ListResourceBundle;

public class StandardButtonResources extends ListResourceBundle {
    public Object[][] getContents() {
        return contents;
    }

    static final Object[][] contents = {
        {StandardButton.ABORT, "Abort"},
        {StandardButton.ABOUT, "About"},
        {StandardButton.ABOUT_, "About..."},
        {StandardButton.ACCEPT, "Accept"},
        {StandardButton.ADD, "Add"},
        {StandardButton.ADD_, "Add..."},
        {StandardButton.ADDPROG, "Add Prog"},
        {StandardButton.ADDPID, "Add PID"},
        {StandardButton.APPLY, "Apply"},
        {StandardButton.BACK, "Back"},
        {StandardButton.BACKGROUND, "Background"},
        {StandardButton.BACKGROUND_, "Background..."},
        {StandardButton.CANCEL, "Cancel"},
        {StandardButton.CENTER, "Center"},
        {StandardButton.CLEAR, "Clear"},
        {StandardButton.CLOSE, "Close"},
        {StandardButton.CONNECT, "Connect"},
        {StandardButton.COPY, "Copy"},
        {StandardButton.CUT, "Cut"},
        {StandardButton.DEFAULT, "Default"},
        {StandardButton.DELETE, "Delete"},
        {StandardButton.DELPROG, "Delete Prog"},
        {StandardButton.DELPID, "Delete PID"},
        {StandardButton.DONE, "Done"},
        {StandardButton.DOWN, "Down"},
        {StandardButton.EDIT, "Edit"},
        {StandardButton.EDIT_, "Edit..."},
        {StandardButton.EXIT, "Exit"},
        {StandardButton.FILE, "File"},
        {StandardButton.FIND, "Find"},
        {StandardButton.FIND_, "Find..."},
        {StandardButton.FINISH, "Finish"},
        {StandardButton.FOREGROUND, "Foreground"},
        {StandardButton.FOREGROUND_, "Foreground..."},
        {StandardButton.FORWARD, "Forward"},
        {StandardButton.GO, "Go"},
        {StandardButton.GO_, "Go..."},
        {StandardButton.HELP, "Help"},
        {StandardButton.HELP_, "Help..."},
        {StandardButton.IGNORE, "Ignore"},
        {StandardButton.INSERT, "Insert"},
        {StandardButton.KILL, "Kill"},
        {StandardButton.LEFT, "Left"},
        {StandardButton.LESS, "Less"},
        {StandardButton.LOGIN, "Login"},
        {StandardButton.LOGIN_, "Login..."},
        {StandardButton.LOG_IN, "Log In"},
        {StandardButton.LOG_IN_, "Log In..."},
        {StandardButton.LOGOUT, "Logout"},
        {StandardButton.LOG_OUT, "Log Out"},
        {StandardButton.MORE, "More"},
        {StandardButton.MORE_, "More..."},
        {StandardButton.MORE__, "..."},
        {StandardButton.MOVE, "Move"},
        {StandardButton.NEW, "New"},
        {StandardButton.NEW_, "New..."},
        {StandardButton.NEXT, "Next"},
        {StandardButton.NO, "No"},
        {StandardButton.NOALL, "No to All"},
        {StandardButton.OK, "OK"},
        {StandardButton.OPEN, "Open"},
        {StandardButton.OPEN_, "Open..."},
        {StandardButton.PASTE, "Paste"},
        {StandardButton.PREVIOUS, "Previous"},
        {StandardButton.PRINT, "Print"},
        {StandardButton.PRINT_, "Print..."},
        {StandardButton.QUIT, "Quit"},
        {StandardButton.REBOOT, "Reboot"},
        {StandardButton.REDO, "Redo"},
        {StandardButton.REJECT, "Reject"},
        {StandardButton.REMOVE, "Remove"},
        {StandardButton.RESTART, "Restart"},
        {StandardButton.RESTORE, "Restore"},
        {StandardButton.RETRY, "Retry"},
        {StandardButton.RIGHT, "Right"},
        {StandardButton.RUN, "Run"},
        {StandardButton.RUN_, "Run..."},
        {StandardButton.SAVE, "Save"},
        {StandardButton.SAVE_AS, "Save As"},
        {StandardButton.SAVE_AS_, "Save As..."},
        {StandardButton.SEARCH, "Search"},
        {StandardButton.SEARCH_, "Search..."},
        {StandardButton.START, "Start"},
        {StandardButton.START_, "Start..."},
        {StandardButton.STOP, "Stop"},
        {StandardButton.UNDO, "Undo"},
        {StandardButton.UP, "Up"},
        {StandardButton.VIEW, "View"},
        {StandardButton.WINDOW, "Window"},
        {StandardButton.YES, "Yes"},
        {StandardButton.CHANGE_HOST_, "Change Host..."},
        {StandardButton.RECONNECT, "Reconnect"},
        {StandardButton.YESALL, "Yes to All"},
        {StandardButton.BROWSE, "Browse"},
    };
}